config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'main#index'

  resources :albums


  resources :stores do 
    resources :albums do
    patch'/add', to: 'albums#add' #for cart
  end
end
resources :artists, except: [:destroy]
resources :genres,  only: [:index, :show]



get '/login', to: 'sessions#login'
post '/login', to: 'sessions#create'
post '/logout', to: 'sessions#destroy'
get '/logout', to: 'sessions#destroy'

get '/user_login', to: 'sessions#user_login'
post '/user_login', to: 'sessions#user_create'

get '/cart', to: 'main#cart'
post '/cart', to: 'main#add_to_cart'
patch '/main/:id', to: 'main#remove'

get '/bouncer', to: "main#bouncer"

get '/most', to: "main#store_most"
  



  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]
  

  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  scope :bougie, -> {order(price: :desc)}
  scope :cheap, -> {order(price: :asc)}
  scope :by_format, -> {order(format: :desc)}




  belongs_to :store
  belongs_to :user, optional: true 
  belongs_to :artist
  belongs_to :genre

  validates :title, presence: true
  validates :format, presence: true
  validates :store_id, presence: true

  validates :title, presence: true
  validates :label, presence: true
  validates :release_date, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :format, presence: true
  validates_numericality_of :price, :only_decimal => true, :greater_than_or_equal_to => 0

  accepts_nested_attributes_for :artist, :genre

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    if not_auth_for_new
      redirect_to '/bouncer'
    else
    current_store
    @album = @store.albums.build
    end
  end

  
  def create
    current_store
    @album = @store.albums.build(album_params)
    if @album.save
      redirect_to store_path(@store)
    else
      album_errors
      render :new
    end
  end
  
  def index
    @artist = Artist.all
    if params[:store_id]
      find_store
      @albums = @store.albums.by_format
    else
      @albums = Album.all
      @stores = Store.all
  end
end
  
  def show
    @album = Album.find_by(id: params[:id])
  end
  
  
def edit
  if not_auth_for_edit
    redirect_to '/bouncer'
   else
     current_store
     find_album
     edit_album_path(@album)
   end
  end


  def update
    find_album
    current_store
      @album.update(album_params)
      if @album.save
        redirect_to store_albums_path(current_store)
    else
      album_errors
      render :edit
    end
  end


  def add  
    if the_current_user == nil
      redirect_to root_path
    else
    @album = Album.find_by(id: params[:album_id])
    @album.user = the_current_user
    @album.save
      redirect_to '/cart'
  end
end
  
  
  def destroy
    current_store
    find_album
    @album.destroy
    redirect_to '/'
  end


  
  private
  
  def album_params
    params.require(:album).permit(:title, :format, :label, :release_date, :store_id, :genre_id, :artist_id, :price, :user_id)
  end


  def not_auth_for_new
    no_one_logged_in || current_user_logged_in || find_store == nil
  end

   def not_auth_for_edit
    no_one_logged_in || current_user_logged_in || !current_store.albums.include?(Album.find_by(id: params[:id])) 
   end


  def album_errors
    flash.now[:error] = @album.errors.full_messages
  end


end

# def no_one_logged_in
#   session[:user_id] == nil and  session[:store_id] == nil
# end

# def user_logged_in
#   !!session[:user_id] == true
# end

# def not_store_album
#   session[:store_id] != Album.find_by(id: params[:id]).store.id
# end


#   def find_album
#     @album = Album.find_by(id: params[:id])
#   end

app/helpers/albums_helper.rb
module AlbumsHelper


def for_store
  params[:store_id]
end

end

app/views/albums/_form.html.erb
<div class= "container">

<%= form_for [@store, @album] do |f| %>


<h5>Choose Genre</h5>
 <%= f.collection_select :genre_id, Genre.order(:name),:id,:name, {:prompt => "Select Genre"} %>
<br><br>

<h5>Choose Artist</h5>
 <%= f.collection_select :artist_id, Artist.order(:name),:id,:name, {:prompt => "Select Artist"} %>
<br><br>

<h5><%= link_to "Or Add New Artist", new_artist_path %></h5>
<br><br>


<h5> Choose Format </h5>
<%= f.select :format, [['Vinyl', 'Vinyl'], ['CD', 'CD'], ['Cassette Tape', 'Cassette Tape']], {:prompt => "Select Format"} %>

<br>
<br>
<%= f.label "Title:" %> <br>
<%= f.text_field :title %>
<br><br>



<%= f.label "Record Label:" %> <br>
<%= f.text_field :label %>
<br><br>

<%= f.label "Release Date:" %> <br>
<%= f.date_field :release_date %>
<br><br>

<%= f.label "Price:" %> <br>
<%= f.number_field :price %>
<br><br><br>


<%= f.submit "#{button_label}", class: 'btn btn-small pink white-text' %>


<% end %>

</div>

app/views/albums/edit.html.erb
<center>
<h3>Edit Album</h3>
</center>
<br>
<%if store_logged_in?%>
  <%= render partial: 'form', locals:{button_label: "make changes"} %>
  <div class= "container">
    <%= button_to "delete album", store_album_path(@album), :method => "delete", class: 'btn btn-small orange white-text'   %>
  </div>
<%end%>

<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

app/views/albums/index.html.erb
<script>
$(document).ready(function(){
    $('.materialboxed').materialbox();
  });
</script> 


<%if for_store%>
<center>
<div class= "container">
<div class= "container">
<div class= "container">
<div class= "container">
<h5 class=><%=@store.name%></h5>
</div>
</div>
</div>
</div>
</center>
<div class= "container">
<img class="materialboxed right" width="400" src="<%= @store.image%>"
</div>
<br>
<%end%>

<% if for_store %>

<% @albums.each do |a|%>
<ul>
<li>
<p><b> <%= @artist.find_by(id: a.artist_id).name%>:  <%=a.title %></b> <i>Format: <%= a.format%></i></p>
<%= button_to "info", album_path(a), :method => "get", class: 'btn btn-small pink white-text'   %> <br>
</li>
</ul>
<% end %>

<% end %>






<% if !for_store%>
<div class= "container">
<%@stores.each do |s| %>
<center>
<div class= "container">
<div class= "container">
<div class= "container">
<h5 class= "grey white-text"><%=s.name%></h5>
</div>
</div>
</div>
<br>
</center>
<% s.albums.each do |a|%>


<b><p> <%= @artist.find_by(id: a.artist_id).name%>:  <%=a.title %></b> <i>Format: <%= a.format%></i></p>

<%end%>
<%= button_to "visit store", store_path(s), :method => "get", class: 'btn btn-small pink white-text'   %> <br>
<%end%>
</div>
<%end%>

app/views/albums/new.html.erb
<center>
<h3>Add Album</h3>
</center>


<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

<%= render partial: 'form', locals:{button_label: "Make New"} %>

app/views/albums/show.html.erb
<center>
<h3><%= Artist.find_by(id: @album.artist_id).name%>:  <%=@album.title %> </h3>
</center>

<div class= "container">

<h6>Format: <%= @album.format%></h6> 
<h6>Genre: <%= Genre.find_by(id: @album.genre_id).name%></h6>
<h6>Release Date: <%= @album.release_date.strftime("%m/%d/%Y")%></h6> 
<h6>Record Label: <%= @album.label%></h6>
<h6>Price: <i> $<%= @album.price%>0 </i> </h6> 

<% if current_store%>
<%= button_to "edit album", edit_album_path(@album), :method => "get", class: 'btn btn-small purple white-text'   %>
<%end%>

<%if current_user%>
<%= button_to "add to cart", store_album_add_path(@album.store, @album), :method => "patch", class: 'btn btn-small purple white-text'   %>
<%end%>