config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'main#index'

  resources :albums


  resources :stores do 
    resources :albums do
    patch'/add', to: 'albums#add' #for cart
  end
end
resources :artists, except: [:destroy]
resources :genres,  only: [:index, :show]



get '/login', to: 'sessions#login'
post '/login', to: 'sessions#create'
post '/logout', to: 'sessions#destroy'
get '/logout', to: 'sessions#destroy'

get '/user_login', to: 'sessions#user_login'
post '/user_login', to: 'sessions#user_create'

get '/cart', to: 'main#cart'
post '/cart', to: 'main#add_to_cart'
patch '/main/:id', to: 'main#remove'

get '/bouncer', to: "main#bouncer"

get '/most', to: "main#store_most"
  



  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]
  

  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<div class="container errors red-text">
  <% if flash[:error] %>
    <% flash[:error].each do |error| %>
      <p><%= error %></p>
    <%end%>
  <%end%>
</div>
  <%= flash[:notice] if flash[:notice] %>

app/views/layouts/_nav.html.erb
 <div class="nav-wrapper">
      <div>
     
      <h4 class = "top right orange"><li><%= link_to "record bae", "/" %></li></h4>
   
      </div>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
         <%if !store_logged_in? && !user_logged_in?%>
        <li><h5 class= "green"><%= link_to "new user", "/users/new" %></h5></li>
        <li><h5 class= "amber"><%= link_to "user log in", "/user_login" %></h5></li>
        <li><h5 class= "grey"><%= link_to "new store", new_store_path %></h5></li>
        <li><h5 class= "red"><%= link_to "store log in", login_path %></h5></li>
        <li><h5 class= "light-blue"><%= link_to "Google User", '/auth/google_oauth2', method: :post %></h5></li>
        <li><h5 class= "teal"><%= link_to "all stores", stores_path %></h5></li>
        <%end%>


        <%if user_logged_in?%>
        <li><h5 class= "green"><%= link_to "log out", logout_path %></h5></li>
        <li><h5 class= "amber"><%= link_to "my profile", user_path(current_user) %></h5></li>
        <li><h5 class= "grey"><%= link_to "my cart", '/cart' %></h5></li>
        <li><h5 class= "red"><%= link_to "all stores", stores_path %></h5></li>
        <li><h5 class= "light-blue"><%= link_to "all albums", albums_path %></h5></li>
        <%end%>
        

        <%if store_logged_in? && !user_logged_in?%>
        <li><h5 class= "green"><%= link_to "log out", logout_path %></h5></li>
        <li><h5 class= "amber"><%= link_to "add album", new_store_album_path(current_store) %></h5></li>
        <li><h5 class= "grey"><%= link_to "your store", store_albums_path(current_store) %></h5></li>
        <li><h5 class= "red"><%= link_to "all stores", stores_path %></h5></li>
        <li><h5 class= "light-blue"><%= link_to "edit store", edit_store_path(current_store) %></h5></li>
        <%end%>
      </ul>
    </div>

app/views/layouts/application.html.erb
<style>
      body {
        background-image: url("" 
);
>;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: bottom right;
        background-size: small;
      }
</style>

<!DOCTYPE html>
<html>
  <head>
    <title>RecordApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

       <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

    <nav class= "white">
   <%= render 'layouts/nav' %>
  </nav>


  <body class= "white">
  <%= render 'layouts/errors' %>
    <%= yield %>
  </body>
</html>